operations:
    marello_inventory_item_enable_batches:
        label: marello.inventory.inventoryitem.enable_batch_inventory.label
        enabled: true
        routes:
            - marello_inventory_inventory_view
            - marello_inventory_inventory_update
        acl_resource: marello_inventory_inventory_update
        applications: [default]
        preconditions:
            '@equal': [$enableBatchInventory, false]
        actions:
            - '@assign_value': [$enableBatchInventory, true]
            - '@flush_entity': $.data
            - '@flash_message':
                  message: marello.inventory.messages.success.inventoryitem.saved
                  type: 'success'
        frontend_options:
            confirmation:
                message: marello.inventory.operations.enable_inventory_batch_confirm
                title: marello.inventory.operations.enable_inventory_batch_title
            options:
                allowMaximize: true
                allowMinimize: true
                dblclick: maximize
                maximizedHeightDecreaseBy: minimize-bar
                width: 500

    marello_inventory_reshipment_create:
        label: marello.inventory.reshipment.button.label
        enabled: true
        button_options:
            class: btn-primary icons-holder-text
        routes:
            - marello_order_order_view
        acl_resource: marello_inventory_inventory_view
        applications: [default]
        preconditions:
            '@and':
                - '@extendable':
                    events: [ extendable_condition.reshipment_allowed ]
        actions:
            - '@redirect':
                  parameters:
                      route: marello_inventory_reshipment_create
                      route_parameters:
                          id: $id
