api:
    entity_aliases:
        Marello\Bundle\InventoryBundle\Entity\BalancedInventoryLevel:
            alias: marellobalancedinventorylevel
            plural_alias: marellobalancedinventorylevels

        Marello\Bundle\InventoryBundle\Entity\WarehouseType:
            alias: marellowarehousetype
            plural_alias: marellowarehousetypes

    entities:
        Marello\Bundle\InventoryBundle\Entity\BalancedInventoryLevel:
            documentation_resource: '@MarelloInventoryBundle/Resources/doc/api/balancedinventorylevel.md'
            fields:
                saleschannels:
                    property_path: salesChannelGroup.salesChannels
                salesChannelGroup:
                    exclude: true
                createdAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        allow_array: true
                        property_path: product.sku
                        description: 'Filter by product sku'
                    saleschannel:
                        data_type: string
                        property_path: salesChannelGroup.salesChannels.code
                        description: 'Filter levels by SalesChannel'
                    createdAt:
                        exclude: true
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter products by updated at'
            actions:
                get_subresource: false
                create: false
                update: false
                delete: false
                delete_list: false
                add_relationship: false
                get_relationship: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\InventoryBundle\Entity\WarehouseType:
            actions: false
