charts:
    marelloinventory:
        label: oro.chart.multiline_chart.label
        data_schema:
          - name: label
            label: oro.chart.multiline_chart.params.label
            required: true
            default_type: day
          - name: value
            label: oro.chart.multiline_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: integer
        default_settings:
            connect_dots_with_line: true
            display_dots: true
            chartColors: ['#ACD39C', '#BE9DE2', '#6598DA', '#ECC87E', '#A4A2F6', '#6487BF', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: MarelloInventoryBundle:Chart:inventory.html.twig
