oro_entity:
    entity_aliases:
        Marello\Bundle\InventoryBundle\Entity\InventoryItem:
            alias: marelloinventoryitem
            plural_alias: marelloinventoryitems

        Marello\Bundle\InventoryBundle\Entity\InventoryLevel:
            alias: marelloinventorylevel
            plural_alias: marelloinventorylevels

        Marello\Bundle\InventoryBundle\Entity\BalancedInventoryLevel:
            alias: marellobalancedinventorylevel
            plural_alias: marellobalancedinventorylevels

        Marello\Bundle\InventoryBundle\Entity\Warehouse:
            alias: marellowarehouse
            plural_alias: marellowarehouses

        Marello\Bundle\InventoryBundle\Entity\WarehouseChannelGroupLink:
            alias: marellowarehousechannelgrouplink
            plural_alias: marellowarehousechannelgrouplinks

        Marello\Bundle\InventoryBundle\Entity\WarehouseGroup:
            alias: marellowarehousegroup
            plural_alias: marellowarehousegroups

        Marello\Bundle\InventoryBundle\Entity\WarehouseType:
            alias: marellowarehousetype
            plural_alias: marellowarehousetypes

        Marello\Bundle\InventoryBundle\Entity\Allocation:
            alias: marelloallocation
            plural_alias: marelloallocation

        Marello\Bundle\InventoryBundle\Entity\AllocationItem:
            alias: marelloallocationitem
            plural_alias: marelloallocationitems