placeholders:
    items:
        marello_inventory_log_chart_item:
            action:     MarelloInventoryBundle:InventoryLog:chart
            applicable: true
        marello_inventory_expected_expired_totals:
            template: '@@MarelloInventory/InventoryItem/inventoryLevelsTotals.html.twig'

    placeholders:
        marello_inventory_log_chart:
            items:
                marello_inventory_log_chart_item: ~

        marello_inventory_levels_totals:
            items:
                marello_inventory_expected_expired_totals:
                    order: 150
