datagrids:
    marello-purchase-order:
        source:
            type: orm
            query:
                select:
                    - po
                from:
                    - { table: MarelloPurchaseOrderBundle:PurchaseOrder, alias: po }
        columns:
            purchaseOrderNumber:
                label:              marello.purchaseorder.purchase_order_number.label
                frontend_type:      string
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
            updatedAt:
                label:              oro.ui.updated_at
                frontend_type:      datetime
        sorters:
            columns:
                purchaseOrderNumber:
                    data_name:      po.purchaseOrderNumber
                createdAt:
                    data_name:      po.createdAt
                updatedAt:
                    data_name:      po.updatedAt
            default:
                purchaseOrderNumber: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC"
        filters:
            columns:
                purchaseOrderNumber:
                    type: string
                    data_name: po.purchaseOrderNumber
                createdAt:
                    type: datetime
                    data_name: po.createdAt
                updatedAt:
                    type: datetime
                    data_name: po.updatedAt
        properties:
            id: ~
            view_link:
                type: url
                route: marello_purchaseorder_purchaseorder_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  marello_purchase_order_view
                rowAction:     true
        action_configuration:
            view: true
            delete: false

    marello-purchase-order-items:
        source:
            type: orm
            query:
                select:
                    - poi
                from:
                    - { table: MarelloPurchaseOrderBundle:PurchaseOrderItem, alias: poi }
                where:
                    and:
                        - IDENTITY(poi.order) = :order_id
            bind_parameters:
                order_id: order_id
        columns:
            productSku:
                label: marello.product.sku.label
                frontend_type: string
            productName:
                label: marello.product.name.label
                frontend_type: string
            supplier:
                label: marello.supplier.entity_label
                frontend_type: string
            status:
                label: marello.purchaseorder.purchaseorderitem.status.label
                frontend_type: string
            orderedAmount:
                label: marello.purchaseorder.purchaseorderitem.ordered_amount.label
                frontend_type: number
            receivedAmount:
                label: marello.purchaseorder.purchaseorderitem.received_amount.label
                frontend_type: number

    marello-purchase-order-item-candidates:
        source:
            type: orm
            query:
                select:
                    - p.id
                    - p.sku
                    - p.name
                    - sup.id AS preferredSupplierId
                    - sup.name AS preferredSupplier
                    - p.desiredStockLevel
                    - p.purchaseStockLevel
                    - COALESCE(SUM(l.inventory - l.allocatedInventory), 0) AS virtualStock
                    - (p.desiredStockLevel - COALESCE(SUM(l.inventory - l.allocatedInventory), 0)) AS orderAmount
                    - >
                      (CASE WHEN p.id IN (:data_in) AND p.id NOT IN (:data_not_in)
                        THEN true ELSE false
                      END) as hasProduct
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.inventoryItems, alias: i }
                        - { join: i.currentLevel, alias: l }
                        - { join: p.status, alias: s }
                        - { join: p.preferredSupplier, alias: sup }
                where:
                    and:
                        - sup.name <> ''
                        - 0 <> :supplierId
                        - s.name = 'enabled'                                          # Only select product with enabled status
                        - p.replenishment = 'never_out_of_stock'

                having: SUM(l.inventory - l.allocatedInventory) < p.purchaseStockLevel  # Only products with virtual stock lower than required purchase stock level
                groupBy: p.id

            bind_parameters:
                - supplierId

        columns:
            hasProduct:
                label:              marello.purchaseorder.has_item.label
                editable:           true
                frontend_type:      boolean
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            name:
                label:              marello.product.name.label
                frontend_type:      string
            preferredSupplier:
                label:              marello.product.preferred_supplier.label
                frontend_type:      string
                data_name:          preferredSupplier
            purchaseStockLevel:
                label:              marello.purchaseorder.purchaseorderitem.purchase_stock_level.label
                frontend_type:      number
            desiredStockLevel:
                label:              marello.purchaseorder.purchaseorderitem.desired_stock_level.label
                frontend_type:      number
            virtualStock:
                label:              marello.purchaseorder.purchaseorderitem.virtual_stock_level.label
                frontend_type:      number
                data_name:          virtualStock
            orderAmount:
                label:              marello.purchaseorder.purchaseorderitem.order_amount.label
                frontend_type:      number
                data_name:          orderAmount
        sorters:
            columns:
                hasProduct:             { data_name: hasProduct }
                sku:                    { data_name: p.sku }
                name:                   { data_name: p.name }
                preferredSupplier:      { data_name: preferredSupplier }
                purchaseStockLevel:     { data_name: p.purchaseStockLevel }
                desiredStockLevel:      { data_name: p.desiredStockLevel }
                virtualStock:           { data_name: virtualStock }
                orderAmount:            { data_name: orderAmount }
            default:
                hasProduct: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                hasProduct:
                    data_name:        hasProduct
                    type:             boolean
                sku:
                    type:             string
                    data_name:        p.sku
                name:
                    type:             string
                    data_name:        p.name
                preferredSupplier:
                    type:             string
                    data_name:        preferredSupplier
                purchaseStockLevel:
                    type:             number
                    data_name:        p.purchaseStockLevel
                desiredStockLevel:
                    type:             number
                    data_name:        p.desiredStockLevel
                virtualStock:
                    type:             number
                    data_name:        virtualStock
                    filter_by_having: true
                orderAmount:
                    type:             number
                    data_name:        orderAmount
                    filter_by_having: true
        properties:
            id: ~
            view_link:
                type: url
                route: marello_product_view
                params:
                    - id
        options:
            entityHint: p
            rowSelection:
                dataField: id
                columnName: hasProduct
                selectors:
                    included: '#appendProducts'
                    excluded: '#removeProducts'
            requireJSModules:
                - marellopurchaseorder/js/datagrid/marello-purchase-order-item-candidates-builder