placeholders:
    placeholders:
        marello_customer_additional_info_subscriptions:
            items:
                marello_customer_subscriptions_grid:
                    order: 10

    items:
        marello_customer_subscriptions_grid:
            template: MarelloSubscriptionBundle:Customer:customerSubscriptionsGrid.html.twig