imports:
    - { resource: controllers.yml }

parameters:
    marello_invoice.pdf.document.total_rows:
        a4: 36
        letter: 33
    marello_invoice.pdf.document.description_width:
        a4: 20
        letter: 20
    marello_invoice.pdf.document.header_rows: 13
    marello_invoice.pdf.document.footer_rows: 3

services:
    marello_invoice.mapper.abstract:
        class: 'Marello\Bundle\InvoiceBundle\Mapper\AbstractInvoiceMapper'
        abstract: true
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'
            - '@oro_entity.doctrine_helper'

    marello_invoice.mapper.order_to_invoice:
        class: 'Marello\Bundle\InvoiceBundle\Mapper\OrderToInvoiceMapper'
        parent: marello_invoice.mapper.abstract
        arguments:
            - '@marello_payment_term.provider.payment_term'

    marello_invoice.mapper.refund_to_creditmemo:
        class: 'Marello\Bundle\InvoiceBundle\Mapper\RefundToCreditmemoMapper'
        parent: marello_invoice.mapper.abstract

    marello_invoice.manager.invoice:
        class: 'Marello\Bundle\InvoiceBundle\Manager\InvoiceManager'
        arguments:
            - '@marello_invoice.mapper.order_to_invoice'
            - '@oro_entity.doctrine_helper'

    marello_invoice.manager.creditmemo:
        class: 'Marello\Bundle\InvoiceBundle\Manager\CreditmemoManager'
        arguments:
            - '@marello_invoice.mapper.refund_to_creditmemo'
            - '@oro_entity.doctrine_helper'

    marello_invoice.listener.invoice_create.manual:
        class: 'Marello\Bundle\InvoiceBundle\EventListener\ManualInvoiceCreationListener'
        arguments:
            - '@marello_invoice.manager.invoice'
        tags:
            - { name: kernel.event_listener, event: extendable_action.order_invoiced, method: onInvoiced, priority: 10 }

    marello_invoice.listener.creditmemo_create.manual:
        class: 'Marello\Bundle\InvoiceBundle\EventListener\ManualCreditmemoCreationListener'
        arguments:
            - '@marello_invoice.manager.creditmemo'
        tags:
            - { name: kernel.event_listener, event: extendable_action.refund_credited, method: onCredited, priority: 10 }

    marello_invoice.listener.datagrid.invoice_grid_address_filter_listener:
        class: 'Marello\Bundle\InvoiceBundle\EventListener\Datagrid\InvoiceGridAddressFilterListener'
        arguments:
            - '@oro_locale.dql.formatter.name'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-invoices-base-grid, method: onBuildBefore }

    marello_invoice.provider.invoice_paid_amount:
        class: 'Marello\Bundle\InvoiceBundle\Provider\InvoicePaidAmountProvider'
        public: true

    marello_invoice.provider.invoice_type_choices:
        class: 'Marello\Bundle\InvoiceBundle\Provider\InvoiceTypeChoicesProvider'
        public: true

    marello_invoice.pdf.invoice.table_provider:
        class: 'Marello\Bundle\InvoiceBundle\Pdf\Table\InvoiceTableProvider'
        arguments:
            - '@marello_invoice.pdf.provider.table_size'
        tags:
            - { name: marello_pdf.document_table_provider }

    marello_invoice.pdf.provider.table_size:
        class: 'Marello\Bundle\PdfBundle\Provider\TableSizeProvider'
        arguments:
            - '@oro_config.saleschannel'
            - '%marello_invoice.pdf.document.total_rows%'
            - '%marello_invoice.pdf.document.description_width%'
            - '%marello_invoice.pdf.document.header_rows%'
            - '%marello_invoice.pdf.document.footer_rows%'

    marello_invoice.pdf.provider.logo_path:
        class: 'Marello\Bundle\InvoiceBundle\Pdf\Logo\InvoiceLogoPathProvider'
        arguments:
            - '@oro_config.manager'
            - '@oro_entity.doctrine_helper'
            - '@oro_attachment.manager'
            - '@oro_attachment.manager.image_resize'
            - '%kernel.project_dir%'

    marello_invoice.pdf.provider.logo_render_parameter:
        class: 'Marello\Bundle\InvoiceBundle\Pdf\Logo\InvoiceLogoRenderParameterProvider'
        arguments:
            - '@marello_invoice.pdf.provider.logo_path'
        tags:
            - { name: marello_pdf.render_parameter_provider }

    marello_invoice.pdf.invoice.request_handler:
        class: 'Marello\Bundle\InvoiceBundle\Pdf\Request\InvoicePdfRequestHandler'
        arguments:
            - '@doctrine'
            - '@translator'
            - '@marello_pdf.provider.render_parameters'
            - '@marello_pdf.renderer.twig'
        tags:
            - { name: marello_pdf.request_handler }

    marello_invoice.pdf.creditmemo.request_handler:
        class: 'Marello\Bundle\InvoiceBundle\Pdf\Request\CreditmemoPdfRequestHandler'
        arguments:
            - '@doctrine'
            - '@translator'
            - '@marello_pdf.provider.render_parameters'
            - '@marello_pdf.renderer.twig'
        tags:
            - { name: marello_pdf.request_handler }


    marello_invoice.pdf.creditmemo.table_provider:
        class: 'Marello\Bundle\InvoiceBundle\Pdf\Table\CreditmemoTableProvider'
        arguments:
            - '@marello_invoice.pdf.provider.table_size'
        tags:
            - { name: marello_pdf.document_table_provider }

    marello_invoice.form_type.invoice_select:
        class: 'Marello\Bundle\InvoiceBundle\Form\Type\InvoiceSelectType'
        tags:
            - { name: form.type }

    marello_invoice.twig.invoice_extension:
        class: 'Marello\Bundle\InvoiceBundle\Twig\InvoiceExtension'
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.extension }
