services:
    marello_inventory.form.type.warehouse:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\WarehouseType'
        tags:
            - { name: form.type }

    marello_inventory.form.type.inventory_item:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\InventoryItemType'
        arguments:
            - '@?marello_inventory.form.event_listener.inventory_item_subscriber'
        tags:
             - { name: form.type }

    marello_inventory.form.type.variant_inventory:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\VariantInventoryType'
        tags:
             - { name: form.type }

    marello_inventory.form.type.inventory_inventorybatch_collection:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\InventoryBatchCollectionType'
        tags:
            - { name: form.type }

    marello_inventory.form.type.inventory_inventorylevel_collection:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\InventoryLevelCollectionType'
        tags:
            - { name: form.type }

    marello_inventory.form.type.inventory_level_manage_batches:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\InventoryLevelManageBatchesType'
        tags:
             - { name: form.type }

    marello_inventory.form.type.inventory_inventorybatch:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\InventoryBatchType'
        arguments:
            - '@marello_inventory.form.event_listener.inventory_batch_subscriber'
        tags:
            - { name: form.type }

    marello_inventory.form.type.inventory_inventorylevel:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\InventoryLevelType'
        arguments:
            - '@marello_inventory.form.event_listener.inventory_level_subscriber'
            - '@event_dispatcher'
        tags:
            - { name: form.type }

    marello_inventory.form.event_listener.inventory_item_subscriber:
        class: 'Marello\Bundle\InventoryBundle\Form\EventListener\InventoryItemSubscriber'
        arguments:
            - '@doctrine'

    marello_inventory.form.event_listener.inventory_batch_subscriber:
        class: 'Marello\Bundle\InventoryBundle\Form\EventListener\InventoryBatchSubscriber'
        arguments:
            - '@marello_inventory.model.inventory_level_calculator'
            - '@event_dispatcher'


    marello_inventory.form.event_listener.inventory_level_subscriber:
        class: 'Marello\Bundle\InventoryBundle\Form\EventListener\InventoryLevelSubscriber'
        arguments:
            - '@marello_inventory.model.inventory_level_calculator'
            - '@event_dispatcher'

    marello_inventory.form.type.inventory_balancer_strategy_choice:
        class: 'Marello\Bundle\InventoryBundle\Form\Type\BalancerStrategyChoiceType'
        arguments:
            - '@marello_inventory.provider.balancer.balancing_strategy_choices_provider'
        tags:
            - { name: form.type }

    Marello\Bundle\InventoryBundle\Form\Type\InventoryAllocationPriorityChoiceType:
        tags:
            - { name: form.type }