parameters:
    marello_inventory.importexport.template_fixture.inventorylevel.class: Marello\Bundle\InventoryBundle\ImportExport\TemplateFixture\InventoryLevelFixture
    marello_inventory.importexport.template_fixture.warehouse.class: Marello\Bundle\InventoryBundle\ImportExport\TemplateFixture\WarehouseFixture
    marello_inventory.inventoryitem.entity.class: Marello\Bundle\InventoryBundle\Entity\InventoryItem
    marello_inventory.inventorylevel.entity.class: Marello\Bundle\InventoryBundle\Entity\InventoryLevel

services:
    marello_inventory.importexport.data_converter:
        class: Marello\Bundle\InventoryBundle\ImportExport\DataConverter\InventoryLevelDataConverter

    marello_inventory.importexport.template_fixture.data_converter.inventorylevel:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    marello_inventory.importexport.strategy.inventory.add_or_replace:
        class: Marello\Bundle\InventoryBundle\ImportExport\Strategy\InventoryLevelUpdateStrategy
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setLevelCalculator, ['@marello_inventory.model.inventory_level_calculator']]

    # Import processor
    marello_inventory.importexport.processor.import.add_or_replace:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@marello_inventory.importexport.data_converter']]
            - [setStrategy, ['@marello_inventory.importexport.strategy.inventory.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%marello_inventory.inventorylevel.entity.class%', alias: marello_inventory.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: '%marello_inventory.inventorylevel.entity.class%', alias: marello_inventory.add_or_replace }

    # Export processor
    marello_inventory.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@marello_inventory.importexport.data_converter']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: '%marello_inventory.inventorylevel.entity.class%', alias: marello_inventorlevel_export }

    marello_inventory.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@marello_inventory.importexport.data_converter']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%marello_inventory.inventorylevel.entity.class%', alias: marello_inventorlevel_export }

    marello_inventory.importexport.template_fixture.inventorylevel:
        class: '%marello_inventory.importexport.template_fixture.inventorylevel.class%'
        tags:
            - { name: oro_importexport.template_fixture }

    marello_inventory.importexport.template_fixture.warehouse:
        class: '%marello_inventory.importexport.template_fixture.warehouse.class%'
        tags:
            - { name: oro_importexport.template_fixture }
