items:
    marello_variant_mass_inventory_link:
        template:   MarelloProductBundle:Inventory:addVariantInventoryLink.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %marello_product.entity.class%)
        acl:        marello_inventory_product_stock_modify
    marello_variant_mass_inventory_button:
        template:   MarelloInventoryBundle:Inventory:addVariantInventoryButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %marello_product.entity.class%)
        acl:        marello_inventory_product_stock_modify