services:
    marello_product.widget_provider.actions.variant_mass_inventory:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_variant_mass_inventory_button
            - marello_variant_mass_inventory_link
        tags:
            - { name: oro_ui.view_action_provider, group: product }

    marello_inventory.logging.chart_builder:
        class: Marello\Bundle\InventoryBundle\Logging\ChartBuilder
        public: true
        arguments:
            - '@marello_inventory.repository.inventorylevellogrecord'
            - '@marello_inventory.model.inventory_level_totals_calculator'
            - '@oro_dashboard.datetime.helper'
            - '@translator'

    marello_inventory.manager.inventory_manager:
        class: 'Marello\Bundle\InventoryBundle\Manager\InventoryManager'
        public: true
        calls:
            - [setContextValidator, ['@marello_inventory.validator.inventory_update_context']]
            - [setDoctrineHelper, ['@oro_entity.doctrine_helper']]
            - [setEventDispatcher, ['@event_dispatcher']]
        lazy: true

    marello_inventory.validator.inventory_update_context:
        class: 'Marello\Bundle\InventoryBundle\Model\InventoryUpdateContextValidator'

    marello_inventory.manager.inventory_item_manager:
        class: 'Marello\Bundle\InventoryBundle\Manager\InventoryItemManager'
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
        lazy: true

    marello_inventory.model.inventory_level_calculator:
        class: 'Marello\Bundle\InventoryBundle\Model\InventoryLevelCalculator'

    marello_inventory.model.inventory_level_totals_calculator:
        class: 'Marello\Bundle\InventoryBundle\Model\InventoryTotalCalculator'
        public: true

    marello_inventory.twig.inventory_total_extension:
        class: 'Marello\Bundle\InventoryBundle\Twig\InventoryTotalExtension'
        arguments:
            - '@marello_inventory.model.inventory_level_totals_calculator'
        tags:
            - { name: twig.extension }

    marello_inventory.twig.warehouse_extension:
        class: 'Marello\Bundle\InventoryBundle\Twig\WarehouseExtension'
        arguments:
            - '@marello_inventory.repository.warehouse'
        tags:
            - { name: twig.extension }

    marello_inventory.provider.order_warehouse:
        class: 'Marello\Bundle\InventoryBundle\Provider\OrderWarehousesProvider'

    marello_inventory.repository.warehouse:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\WarehouseRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\Warehouse'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.repository.warehousegroup:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\WarehouseGroupRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\WarehouseGroup'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.repository.warehousechannelgrouplink:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\WarehouseChannelGroupLinkRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\WarehouseChannelGroupLink'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.balancer_strategy.registry:
        class: 'Marello\Bundle\InventoryBundle\Strategy\BalancerStrategiesRegistry'

    marello_inventory.balancer_strategy.equal_division_strategy:
        class: 'Marello\Bundle\InventoryBundle\Strategy\EqualDivision\EqualDivisionBalancerStrategy'
        tags:
            - { name: marello_inventory_balancer_strategy }

    marello_inventory.model.balancer.inventory_balancer:
        class: 'Marello\Bundle\InventoryBundle\Model\InventoryBalancer\InventoryBalancer'
        arguments:
            - '@marello_inventory.balancer_strategy.registry'
            - '@marello_inventory.manager.inventory_item_manager'
            - '@marello_inventory.model.balancedinventory.balanced_inventory_handler'
            - '@oro_config.manager'

    marello_inventory.model.balancer.inventorybalancer_trigger_calculator:
        class: 'Marello\Bundle\InventoryBundle\Model\InventoryBalancer\InventoryBalancerTriggerCalculator'
        arguments:
            - '@oro_config.manager'

    marello_inventory.provider.balancer.balancing_strategy_choices_provider:
        class: 'Marello\Bundle\InventoryBundle\Provider\BalancingStrategyChoicesProvider'
        arguments:
            - '@marello_inventory.balancer_strategy.registry'
            - '@translator'

    marello_inventory.provider.available_inventory_provider:
        class: 'Marello\Bundle\InventoryBundle\Provider\AvailableInventoryProvider'
        arguments:
            - '@oro_entity.doctrine_helper'

    marello_inventory.provider.available_inventory_form_provider:
        class: 'Marello\Bundle\InventoryBundle\Provider\AvailableInventoryFormProvider'
        arguments:
            - '@marello_inventory.provider.available_inventory_provider'
        tags:
            - { name: marello_order.order_item_data_provider, type: inventory, priority: 15 }

    marello_inventory.model.balancedinventory.balanced_inventory_handler:
        class: 'Marello\Bundle\InventoryBundle\Model\BalancedInventory\BalancedInventoryHandler'
        arguments:
            - '@doctrine'
            - '@marello_inventory.model.balancedinventory.balanced_inventory_factory'

    marello_inventory.model.balancedinventory.balanced_inventory_factory:
        class: 'Marello\Bundle\InventoryBundle\Model\BalancedInventory\BalancedInventoryFactory'

    marello_inventory.manager.balancedinventory_manager:
        class: 'Marello\Bundle\InventoryBundle\Manager\BalancedInventoryManager'
        calls:
            - [setBalancedInventoryHandler, ['@marello_inventory.model.balancedinventory.balanced_inventory_handler']]
            - [setContextValidator, ['@marello_inventory.validator.inventory_update_context']]
            - [setEventDispatcher, ['@event_dispatcher']]
        lazy: true

    marello_inventory.async.inventory_rebalance_products_processor:
        class: 'Marello\Bundle\InventoryBundle\Async\InventoryRebalanceProductsProcessor'
        arguments:
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@marello_product.repository.product'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    marello_inventory.async.inventory_rebalance_product_processor:
        class: 'Marello\Bundle\InventoryBundle\Async\InventoryRebalanceProductProcessor'
        arguments:
            - '@marello_inventory.model.balancer.inventory_balancer'
            - '@logger'
            - '@doctrine'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    marello_inventory.async.balanced_inventory_reset_processor:
        class: 'Marello\Bundle\InventoryBundle\Async\BalancedInventoryResetProcessor'
        arguments:
            - '@logger'
            - '@oro_entity.doctrine_helper'
            - '@marello_inventory.model.balancedinventory.balanced_inventory_handler'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    marello_inventory.repository.balancedinventory:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\BalancedInventoryRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\BalancedInventoryLevel'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.repository.inventorylevellogrecord:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\InventoryLevelLogRecordRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\InventoryLevelLogRecord'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.repository.inventoryitem:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\InventoryItemRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\InventoryItem'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.repository.inventorylevel:
        class: 'Marello\Bundle\InventoryBundle\Entity\Repository\InventoryLevelRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\InventoryLevel'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_inventory.form.inventory_order_on_demand_validator:
        class: 'Marello\Bundle\InventoryBundle\Validator\InventoryOrderOnDemandValidator'
        calls:
            - [setConfigManager, ['@oro_config.manager']]
        tags:
            - { name: validator.constraint_validator, alias: marello_inventory.order_on_demand_validator }

    marello_inventory.command.inventory_rebalance:
        class: 'Marello\Bundle\InventoryBundle\Command\InventoryBalanceCommand'
        arguments:
            - '@doctrine'
            - '@marello_inventory.model.balancer.inventory_balancer'
            - '@oro_message_queue.client.message_producer'
        tags:
            - { name: console.command }

    Marello\Bundle\InventoryBundle\Provider\InventoryAllocationProvider:
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@marello_inventory.provider.order_warehouse'
            - '@event_dispatcher'