Marello\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRule:
    properties:
        destinations:
            - Valid: ~
        methodConfigs:
            - Valid: ~
            - Count:
                min: 1
                minMessage: marello.payment.paymentrule.method.config.count.message
        currency:
            - Currency: ~
            - NotBlank: ~
        rule:
            - Valid: ~

Marello\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRuleDestination:
    properties:
        country:
            - NotBlank: ~
            - Valid: ~
        region:
            - Valid: ~

Marello\Bundle\PaymentBundle\Entity\PaymentMethodConfig:
    properties:
        method:
            - NotBlank: ~

Marello\Bundle\PaymentBundle\Entity\Payment:
    constraints:
        - Marello\Bundle\PaymentBundle\Validator\Constraints\PaymentStatus: ~