api:
    entity_aliases:
        Marello\Bundle\ShippingBundle\Entity\Shipment:
            alias: marelloshipment
            plural_alias: marelloshipments

    entities:
        Marello\Bundle\ShippingBundle\Entity\Shipment:
#            documentation_resource: '@MarelloInvoiceBundle/Resources/doc/api/invoice.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
