api:
    entities:
        Marello\Bundle\ShippingBundle\Entity\Shipment:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
