marelloenterprise_inventory_warehouse:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WarehouseController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse

marelloenterprise_inventory_warehousegroup:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WarehouseGroupController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse-group

marelloenterprise_inventory_warehousechannelgrouplink:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WarehouseChannelGroupLinkController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse-channelgroup-link

marelloenterprise_inventory_wfarule:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WFARuleController.php"
    type:     annotation
    prefix:   /marello/inventory/wfa-rule

marelloenterprise_api_enable_wfa_rule:
    path: '/api/rest/{version}/wfarules/{id}/enable'
    methods: [GET]
    defaults:
        _controller: 'MarelloEnterprise\Bundle\InventoryBundle\Controller\Api\Rest\WFARuleController::enableAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

marelloenterprise_api_disabe_wfa_rule:
    path: '/api/rest/{version}/wfarules/{id}/disable'
    methods: [GET]
    defaults:
        _controller: 'MarelloEnterprise\Bundle\InventoryBundle\Controller\Api\Rest\WFARuleController::disableAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

marelloenterprise_api_mass_wfa_rule:
    path: '/api/rest/{version}/wfarules/{gridName}/massAction/{actionName}'
    methods: [GET]
    defaults:
        _controller: 'MarelloEnterprise\Bundle\InventoryBundle\Controller\Api\Rest\WFARuleController::massAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1
