services:
    marello_refund.workflow.create_refund_action:
        class: Marello\Bundle\RefundBundle\Workflow\Actions\CreateRefundAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
        tags:
            - { name: oro_action.action, alias: marello_create_refund }

    marello_refund.twig.refund_extension:
        class: Marello\Bundle\RefundBundle\Twig\RefundExtension
        arguments:
            - '@oro_workflow.manager'
            - '@marello_refund.calculator.refund_balance'
        tags:
            - { name: twig.extension }

    marello_refund.api.add_workflow_item_config:
        class: 'Marello\Bundle\WorkflowBundle\Api\Processor\ProcessWorkflowItemConfig'
        tags:
            - { name: oro.api.processor, action: get_config, class: Marello\Bundle\RefundBundle\Entity\Refund }

    marello_refund.api.add_workflow_item:
        class: 'Marello\Bundle\WorkflowBundle\Api\Processor\ProcessWorkflowItem'
        arguments:
            - '@oro_workflow.manager'
            - '@oro_entity.doctrine_helper'
            - '@translator.default'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Marello\Bundle\RefundBundle\Entity\Refund }

    marello_refund.datagrid.action_permission_provider:
        class: 'Marello\Bundle\RefundBundle\Datagrid\RefundActionPermissionProvider'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_refund.calculator.refund_balance:
        class: 'Marello\Bundle\RefundBundle\Calculator\RefundBalanceCalculator'
        arguments:
            - '@doctrine'
        calls:
            - [setTaxCalculator, ['@marello_tax.calculator']]
            - [setTaxRuleMatcher, ['@marello_tax.tax_rule.matcher.composite']]

    marello_refund.validator.refund_balance:
        class: 'Marello\Bundle\RefundBundle\Validator\RefundBalanceValidator'
        arguments:
            - '@marello_refund.calculator.refund_balance'
        tags:
            - { name: validator.constraint_validator, alias: marello_refund.refund_balance_validator }

    marello_refund.provider.form_changes.balance_totals:
        class: Marello\Bundle\RefundBundle\Provider\RefundBalanceTotalsProvider
        arguments:
            - '@marello_refund.calculator.refund_balance'
            - '@oro_currency.rounding.price_rounding_service'
            - '@translator'
        tags:
            - { name: marello.form_changes_data_provider, class: 'Marello\Bundle\RefundBundle\Entity\Refund', type: balance_totals, priority: 40 }

    marello_refund.provider.form_changes.totals:
        class: Marello\Bundle\RefundBundle\Provider\RefundTotalsProvider
        arguments:
            - '@marello_refund.calculator.refund_balance'
            - '@oro_currency.rounding.price_rounding_service'
            - '@translator'
        tags:
            - { name: marello.form_changes_data_provider, class: 'Marello\Bundle\RefundBundle\Entity\Refund', type: totals, priority: 30 }
