oro_api:
    actions:
        authenticate:
            processing_groups:
                initialize:
                    priority: -10
                resource_check:
                    priority: -20
                normalize_input:
                    priority: -30
                security_check:
                    priority: -40
                load_data:
                    priority: -50
                transform_data:
                    priority: -60
                normalize_data:
                    priority: -70
                finalize:
                    priority: -80
                normalize_result:
                    priority: -90
        options:
            processing_groups:
                initialize:
                    priority: -10
                resource_check:
                    priority: -20
                normalize_input:
                    priority: -30
                security_check:
                    priority: -40
                load_data:
                    priority: -50
                transform_data:
                    priority: -60
                normalize_data:
                    priority: -70
                finalize:
                    priority: -80
                normalize_result:
                    priority: -90