navigation:
    menu_config:
        items:
            sales_tab:
                label: 'marello.sales.navigation.sales.label'
                uri: '#'
                extras:
                    icon: fa-shopping-cart
                    position: 20

            sales_channels:
                label: marello.sales.saleschannel.entity_plural_label
                uri: '#'
                extras:
                    position: 50

            sales_channel:
                label: marello.sales.saleschannel.entity_plural_label
                route: marello_sales_saleschannel_index
                extras:
                    routes: ['marello_sales_saleschannel_*']
                    position: 10
            sales_channel_group:
                label: marello.sales.saleschannelgroup.entity_plural_label
                route: marello_sales_saleschannelgroup_index
                extras:
                    routes: ['marello_sales_saleschannelgroup_*']
                    position: 20

            shortcut_new_saleschannel:
                label: 'marello.sales.saleschannel.menu.shortcut_new_saleschannel.label'
                route: 'marello_sales_saleschannel_create'
                extras:
                    description: 'marello.sales.saleschannel.menu.shortcut_new_saleschannel.description'
                    isCustomAction: true

            shortcut_list_saleschannel:
                label: 'marello.sales.saleschannel.menu.shortcut_list_saleschannel.label'
                route: 'marello_sales_saleschannel_index'
                extras:
                    description: 'marello.sales.saleschannel.menu.shortcut_list_saleschannel.description'
                    isCustomAction: true
        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            sales_channels:
                                children:
                                    sales_channel: ~
                                    sales_channel_group: ~
            shortcuts:
                children:
                    shortcut_new_saleschannel: ~
                    shortcut_list_saleschannel: ~

    titles:
        marello_sales_saleschannel_index:   'marello.sales.saleschannel.entity_plural_label'
        marello_sales_saleschannel_create:  'oro.ui.create_entity'
        marello_sales_saleschannel_update:  '%name% - oro.ui.edit'
        marello_sales_saleschannel_view:  '%name% - oro.ui.view'
        marello_sales_saleschannelgroup_index:   'marello.sales.saleschannelgroup.entity_plural_label'
        marello_sales_saleschannelgroup_create:  'oro.ui.create_entity'
        marello_sales_saleschannelgroup_update:  '%name% - oro.ui.edit'
        marello_sales_saleschannelgroup_view:  '%name% - oro.ui.view'
