services:
    marelloenterprise_sales.event_listener.doctrine.organization.create:
        class: 'MarelloEnterprise\Bundle\SalesBundle\EventListener\Doctrine\OrganizationCreateListener'
        arguments:
            - '%installed%'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\OrganizationBundle\Entity\Organization', event: postPersist, priority: 20 }

    marelloenterprise_sales.event_listener.doctrine.sales_channel_group:
        class: 'MarelloEnterprise\Bundle\SalesBundle\EventListener\Doctrine\SalesChannelGroupListener'
        arguments:
            - '@session'
            - '@oro_security.acl_helper'
        tags:
            - { name: doctrine.event_listener, event: preRemove, priority: 20 }
