aliases:
    oro/select2-autocomplete-system-group-sales-channels-component$: marellosales/js/app/components/select2-autocomplete-system-group-sales-channels-component
dynamic-imports:
    marellosales:
        - marellosales/js/app/components/sales-channel-select-component
        - marellosales/js/app/components/select2-autocomplete-system-group-sales-channels-component
    commons:
        - oro/select2-autocomplete-system-group-sales-channels-component