aliases:
    oro/select2-autocomplete-owner-aware-warehouse-group-component$: marelloenterpriseinventory/js/app/components/select2-autocomplete-owner-aware-warehouse-group-component
dynamic-imports:
    marelloenterpriseinventory:
        - marelloenterpriseinventory/js/app/views/inventorylevel-item-view
        - marelloenterpriseinventory/js/app/components/select2-autocomplete-owner-aware-warehouse-group-component
    commons:
        - oro/select2-autocomplete-owner-aware-warehouse-group-component
        - marelloenterpriseinventory/js/app/views/warehouse-grid-view
