imports:
    - { resource: controllers.yml }

services:
    marelloenterprise_inventory.datagrid.warehouse.action_permission_provider:
        public: true
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Datagrid\WarehouseActionPermissionProvider'

    marelloenterprise_inventory.datagrid.warehousegroup.action_permission_provider:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Datagrid\WarehouseGroupActionPermissionProvider'
        public: true
        arguments:
            - '@marelloenterprise_inventory.checker.warehousegroup.is_fixed'

    marelloenterprise_inventory.validator.default_warehouse_exists:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Validator\DefaultWarehouseExistsValidator'
        arguments:
            - '@MarelloEnterprise\Bundle\InventoryBundle\Entity\Repository\WarehouseRepository'
            - '@oro_security.acl_helper'
        tags:
            - { name: validator.constraint_validator, alias: marelloenterprise_inventory.default_warehouse_exists }

    marelloenterprise_inventory.validator.warehouse_added_to_linked_group:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Validator\WarehouseAddedToLinkedGroupValidator'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: marelloenterprise_inventory.warehouse_added_to_linked_group }

    marelloenterprise_inventory.validator.fixed_warehouse_type_linking:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Validator\FixedWarehouseTypeLinkingValidator'
        arguments:
            - '@marelloenterprise_inventory.checker.warehousegroup.is_fixed'
        tags:
            - { name: validator.constraint_validator, alias: marelloenterprise_inventory.fixed_warehouse_type_linking }

    marelloenterprise_inventory.checker.warehousegroup.is_fixed:
        class:  'MarelloEnterprise\Bundle\InventoryBundle\Checker\IsFixedWarehouseGroupChecker'

    marelloenterprise_inventory.twig.warehouse_extension:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Twig\WarehouseExtension'
        public: false
        arguments:
            - '@marelloenterprise_inventory.checker.warehousegroup.is_fixed'
        tags:
            - { name: twig.extension }

    marelloenterprise_inventory.metadata.warehouse:
        class: 'Doctrine\ORM\Mapping\ClassMetadata'
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\Warehouse'

    marelloenterprise_inventory.metadata.warehousechannelgrouplink:
        class: 'Doctrine\ORM\Mapping\ClassMetadata'
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\WarehouseChannelGroupLink'

    MarelloEnterprise\Bundle\InventoryBundle\Entity\Repository\WarehouseRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\InventoryBundle\Entity\Warehouse'
        tags:
            - { name: doctrine.repository_service }

    marelloenterprise_inventory.repository.warehousechannelgrouplink:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Entity\Repository\WarehouseChannelGroupLinkRepository'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@marelloenterprise_inventory.metadata.warehousechannelgrouplink'
            - '@oro_security.acl_helper'

    marelloenterprise_inventory.datagrid.wfa_rule_actions_visibility_provider:
        public: true
        parent: marello_rule.action.visibility_provider

    marelloenterprise_inventory.wfa_strategy.min_distance:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Strategy\WFA\MinimumDistance\MinimumDistanceWFAStrategy'
        arguments:
            - '@marelloenterprise_address.distance_calculator.main'
        tags:
            - { name: marello_inventory_wfa_strategy }

    marelloenterprise_inventory.provider.wfa_strategy.choices:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Provider\WFAStrategyChoicesProvider'
        public: true
        arguments:
            - '@Marello\Bundle\InventoryBundle\Strategy\WFA\WFAStrategiesRegistry'
            - '@translator'

    marelloenterprise_inventory.provider.order_warehouse:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Provider\OrderWarehousesProvider'
        decorates: Marello\Bundle\InventoryBundle\Provider\OrderWarehousesProvider
        arguments:
            - '@Marello\Bundle\InventoryBundle\Strategy\WFA\WFAStrategiesRegistry'
            - '@marello_rule.rule_filtration.service'
            - '@MarelloEnterprise\Bundle\InventoryBundle\Entity\Repository\WFARuleRepository'
            - '@oro_security.acl_helper'

    marelloenterprise_inventory.formatter.wfa_strategy.label:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Formatter\WFAStrategyLabelFormatter'
        arguments:
            - '@Marello\Bundle\InventoryBundle\Strategy\WFA\WFAStrategiesRegistry'
            - '@translator'

    marelloenterprise_inventory.twig.wfa_strategy_extension:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Twig\WFAStrategyExtension'
        public: false
        arguments:
            - '@marelloenterprise_inventory.formatter.wfa_strategy.label'
        tags:
            - { name: twig.extension }

    MarelloEnterprise\Bundle\InventoryBundle\Entity\Repository\WFARuleRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'MarelloEnterprise\Bundle\InventoryBundle\Entity\WFARule'
        tags:
            - { name: doctrine.repository_service }

    Marello\Bundle\InventoryBundle\Strategy\WFA\Quantity\Calculator\SingleWHCalculator:
        calls:
            - ['setSuccessor', ['@MarelloEnterprise\Bundle\InventoryBundle\Strategy\WFA\Quantity\Calculator\MultiWHCalculator']]

    MarelloEnterprise\Bundle\InventoryBundle\Strategy\WFA\Quantity\Calculator\MultiWHCalculator: ~

    marelloenterprise_inventory.action.handler.wfa_rule.enable_status:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Action\Handler\WfaRuleToggleStatusActionHandler'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - true

    marelloenterprise_inventory.action.handler.wfa_rule.disable_status:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Action\Handler\WfaRuleToggleStatusActionHandler'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - false

    MarelloEnterprise\Bundle\InventoryBundle\Provider\InventoryAllocationProvider:
        decorates: Marello\Bundle\InventoryBundle\Provider\InventoryAllocationProvider
        arguments:
            - '@MarelloEnterprise\Bundle\InventoryBundle\Provider\InventoryAllocationProvider.inner'
            - '@Marello\Bundle\InventoryBundle\Strategy\WFA\WFAStrategiesRegistry'
            - '@marello_rule.rule_filtration.service'
            - '@oro_entity.doctrine_helper'
            - '@Marello\Bundle\InventoryBundle\Provider\OrderWarehousesProvider'
            - '@event_dispatcher'