services:
    marelloenterprise_order.workflow.order_ship_action:
        class: 'Marello\Bundle\OrderBundle\Workflow\OrderShipAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@event_dispatcher'
        tags:
            - { name: oro_action.action, alias: marello_ship_order }