acls:
    marello_customer_company_create:
        type: entity
        class: MarelloCustomerBundle:Company
        permission: CREATE

    marello_customer_company_view:
        type: entity
        class: MarelloCustomerBundle:Company
        permission: VIEW

    marello_customer_company_update:
        type: entity
        class: MarelloCustomerBundle:Company
        permission: EDIT

    marello_customer_view:
        type: entity
        class: MarelloCustomerBundle:Customer
        permission: VIEW

    marello_customer_create:
        type: entity
        class: MarelloCustomerBundle:Customer
        permission: CREATE

    marello_customer_update:
        type: entity
        class: MarelloCustomerBundle:Customer
        permission: EDIT
