datagrids:
    marello-taxcode-grid:
        source:
            type: orm
            query:
                select:
                    - t
                from:
                    - { table: MarelloTaxBundle:TaxCode, alias: t }
        columns:
            code:
                label:            marello.tax.taxcode.code.label
                frontend_type:    string
            description:
                label:            marello.tax.taxcode.description.label
                frontend_type:    string
        sorters:
            columns:
                code:
                    data_name: t.code
                description:
                    data_name: t.description
            default:
                code: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        filters:
            columns:
                code:
                    type:       string
                    data_name:  t.code
                description:
                    type:       string
                    data_name:  t.description
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_tax_taxcode_view
                params:     [ id ]
        actions:
            view:
                type:           navigate
                link:           view_link
                icon:           eye
                rowAction:      true
        options:
            export: true

    marello-taxrate-grid:
        source:
            type: orm
            query:
                select:
                    - t
                from:
                    - { table: MarelloTaxBundle:TaxRate, alias: t }
        columns:
            code:
                label:            marello.tax.taxrate.code.label
                frontend_type:    string
            rate:
                label:            marello.tax.taxrate.rate.label
                type:             twig
                frontend_type:    html
                template:         MarelloTaxBundle:TaxRate/DataGrid:rate.html.twig
        sorters:
            columns:
                code:
                    data_name: t.code
                rate:
                    data_name: t.rate
            default:
                code: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        filters:
            columns:
                code:
                    type:       string
                    data_name:  t.code
                rate:
                    type:       string
                    data_name:  t.rate
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_tax_taxrate_view
                params:     [ id ]
        actions:
            view:
                type:           navigate
                link:           view_link
                icon:           eye
                rowAction:      true
        options:
            export: true

    marello-taxrule-grid:
        source:
            type: orm
            query:
                select:
                    - t
                    - tc.code as code
                    - tr.rate as rate
                    - tj.code as jurisdiction
                from:
                    - { table: MarelloTaxBundle:TaxRule, alias: t }
                join:
                    left:
                        - { join: t.taxCode, alias: tc }
                        - { join: t.taxRate, alias: tr }
                        - { join: t.taxJurisdiction, alias: tj }
        columns:
            code:
                label:            marello.tax.taxrule.tax_code.label
                frontend_type:    string
            rate:
                label:            marello.tax.taxrule.tax_rate.label
                type:             twig
                frontend_type:    html
                template:         MarelloTaxBundle:TaxRate/DataGrid:rate.html.twig
            jurisdiction:
                label:            marello.tax.taxrule.tax_jurisdiction.label
                frontend_type:    string
        sorters:
            columns:
                code:
                    data_name: code
                rate:
                    data_name: rate
                jurisdiction:
                    data_name: jurisdiction
            default:
                code: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        filters:
            columns:
                code:
                    type:       string
                    data_name:  code
                rate:
                    type:       string
                    data_name:  rate
                jurisdiction:
                    type:       string
                    data_name:  jurisdiction
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_tax_taxrule_view
                params:     [ id ]
        actions:
            view:
                type:           navigate
                link:           view_link
                icon:           eye
                rowAction:      true
        options:
            export: true

    marello-taxjurisdiction-grid:
        acl_resource: marello_tax_taxjurisdiction_view
        source:
            type: orm
            query:
                select:
                    - jurisdiction.id
                    - jurisdiction.code
                    - jurisdiction.description
                    - jurisdiction.createdAt
                    - jurisdiction.updatedAt
                from:
                    - { table: MarelloTaxBundle:TaxJurisdiction, alias: jurisdiction }
        columns:
            code:
                label: marello.tax.taxjurisdiction.code.label
            description:
                label: marello.tax.taxjurisdiction.description.label
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: jurisdiction.code
                description:
                    data_name: jurisdiction.description
                createdAt:
                    data_name: tax_code.createdAt
                updatedAt:
                    data_name: tax_code.updatedAt
            disable_default_sorting: true
        filters:
            columns:
                code:
                    type:      string
                    data_name: jurisdiction.code
                description:
                    type:      string
                    data_name: jurisdiction.description
                createdAt:
                    type:      datetime
                    data_name: tax_code.createdAt
                updatedAt:
                    type:      datetime
                    data_name: tax_code.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_tax_taxjurisdiction_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  marello_tax_taxjurisdiction_view
                rowAction:     true
