Marello\Bundle\AddressBundle\Entity\Address:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
    constraints: ~

Marello\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        product:
            - NotBlank: ~
        price:
            - NotBlank: ~
        tax:
            - NotBlank: ~
        totalPrice:
            - NotBlank: ~
    constraints: ~
