Marello\Bundle\AddressBundle\Entity\MarelloAddress:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
        country:
            - NotBlank: ~
        phone:
            - Length:
                max: 255
    constraints:
        - Oro\Bundle\AddressBundle\Validator\Constraints\ValidRegion: ~

Marello\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        product:
            - NotBlank: ~
        price:
            - NotBlank: ~
        tax:
            - NotBlank: ~
        taxCode:
            - NotBlank: ~
        rowTotalInclTax:
            - NotBlank: ~
        rowTotalExclTax:
            - NotBlank: ~
    constraints:
        - Marello\Bundle\OrderBundle\Validator\Constraints\AvailableInventory:
            fields: [quantity, order, product]
            errorPath: quantity

Marello\Bundle\OrderBundle\Entity\Order:
    properties:
        customer:
            - NotBlank: ~
        salesChannel:
            - NotBlank: ~
        billingAddress:
            - NotBlank:
                message: 'marello.order.address.validation.billing_not_blank'
        shippingAddress:
            - NotBlank:
                message: 'marello.order.address.validation.shipping_not_blank'
