Marello\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        product:
            - NotBlank: { groups: [api, Default] }
        price:
            - NotBlank: { groups: [api, Default] }
        tax:
            - NotBlank: { groups: [api, Default] }
        taxCode:
            - NotBlank: { groups: [api, Default] }
        rowTotalInclTax:
            - NotBlank: { groups: [api, Default] }
        rowTotalExclTax:
            - NotBlank: { groups: [api, Default] }
        quantity:
            - GreaterThanOrEqual: { groups: [api, Default], value: 1 }
    constraints:
        - Marello\Bundle\OrderBundle\Validator\Constraints\AvailableInventory:
            fields: [quantity, order, product]
            errorPath: quantity
            groups: [api, Default]

Marello\Bundle\OrderBundle\Entity\Order:
    properties:
        customer:
            - NotBlank: ~
        salesChannel:
            - NotBlank: ~
        paymentMethod:
            - NotBlank: ~
        shippingMethod:
            - NotBlank: ~
        billingAddress:
            - NotBlank:
                message: 'marello.order.address.validation.billing_not_blank'
        shippingAddress:
            - NotBlank:
                message: 'marello.order.address.validation.shipping_not_blank'
        grandTotal:
            - GreaterThanOrEqual:
                value: 0
                # property that is responsible for grandTotal < 0 is probably discountAmount, however this is an assumption
                message: 'marello.order.discount_amount.validation.discount_lower_than_subtotal'
        items:
            - Valid: ~
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\GreaterThanDate:
            field: 'deliveryDate'
            greaterThan: 'today'
            nullable: true
            errorPath: deliveryDate
            message: 'marello.order.delivery_date.messages.error.greater_than_date'
