services:
    marello_core.workflow.action.workflow_transit_action:
        class: Marello\Bundle\CoreBundle\Workflow\Action\WorkflowTransitAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_workflow.manager'
        tags:
            - { name: oro_action.action, alias: marello_core_transit_complete_action }

    marello_core.validator.unique.unique_entity_collection:
        class: Marello\Bundle\CoreBundle\Validator\UniqueEntityCollectionValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: unique_entity_collection }

    marello_core.validator.greater_than_date:
        class: Marello\Bundle\CoreBundle\Validator\GreaterThanDateValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: greater_than_date }

    marello_core.greater_than_or_equal_to_value_validator:
        class: Marello\Bundle\CoreBundle\Validator\GreaterThanOrEqualToValueValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: marello_core.greater_than_or_equal_to_value_validator }

    marello_core.twig.core_extension:
        class: Marello\Bundle\CoreBundle\Twig\CoreExtension
        calls:
          - [ setPlaceholderProvider, ['@marello_core.provider.additional_placeholder_provider'] ]
        tags:
            - { name: twig.extension }

    marello_core.twig.workflow_extension:
        class: Marello\Bundle\CoreBundle\Twig\WorkflowExtension
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: twig.extension }

    marello_core.form.url_generator:
        class: Marello\Bundle\CoreBundle\Form\UrlGenerator
        public: true
        arguments:
            - '@oro_platform.provider.package'
            - '@oro_platform.url.cache'
            - '@request_stack'

    marello_core.entity_serializer:
        class: 'Marello\Bundle\CoreBundle\Serializer\EntitySerializer'
        arguments:
            - '@doctrine'
            - '@oro_entity_config.config_manager'
            - '@oro_soap.entity_serializer.entity_accessor'
            - '@oro_soap.entity_serializer.data_transformer'
            - '@oro_soap.entity_serializer.query_factory'
            - '@oro_workflow.manager'
        calls:
            - ["setFieldFilter", ['@oro_security.entity_serializer.field_filter']]

    marello_core.provider.additional_placeholder_provider:
        class: 'Marello\Bundle\CoreBundle\Provider\AdditionalPlaceholderProvider'

    marello_core.twig.file_extension:
        class: 'Marello\Bundle\CoreBundle\Twig\FileExtension'
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: twig.extension }

    marello_core.event_listener.refresh_context:
        class: Marello\Bundle\CoreBundle\EventListener\RefreshContextListener
        decorates: oro_security.listener.refresh_context_listener
        parent: oro_security.listener.refresh_context_listener
