datagrids:
    marello-packingslips:
        source:
            type: orm
            query:
                select:
                    - ps
                    - o.orderNumber
                from:
                    - { table: MarelloPackingBundle:PackingSlip, alias: ps }
                join:
                    left:
                        - { join: ps.order, alias: o }
                        - { join: ps.salesChannel, alias: sc}
                        - { join: ps.warehouse, alias: wh}
                        - { join: ps.billingAddress, alias: ba }
                        - { join: ps.shippingAddress, alias: sa }
        columns:
            packingSlipNumber:
                label:            marello.packing.packingslip.packing_slip_number.label
                frontend_type:    string
            orderNumber:
                label:            marello.packing.packingslip.order.label
            salesChannel:
                label:            marello.packing.packingslip.sales_channel.label
            warehouse:
                label:            marello.packing.packingslip.warehouse.label
            billingAddress:
                frontend_type:    string
                data_name:        billingName # This alias is generated using GridAddressFilterListener
                label:            marello.packing.packingslip.billing_address.name.label
            shippingAddress:
                frontend_type:    string
                data_name:        shippingName # This alias is generated using GridAddressFilterListener
                label:            marello.packing.packingslip.shipping_address.name.label
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
            updatedAt:
                label:            oro.ui.updated_at
                frontend_type:    datetime
        sorters:
            columns:
                packingSlipNumber:
                    data_name: ps.packingSlipNumber
                orderNumber:
                    data_name: o.orderNumber
                salesChannel:
                    data_name: sc.name
                warehouse:
                    data_name: wh.name
                billingAddress:
                    data_name: ps.billingAddress
                shippingAddress:
                    data_name: ps.shippingAddress
                createdAt:
                    data_name: ps.createdAt
                updatedAt:
                    data_name: ps.updatedAt
            default:
                packingSlipNumber: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC"
        filters:
            columns:
                packingSlipNumber:
                    type: string
                    data_name: ps.packingSlipNumber
                orderNumber:
                    type: string
                    data_name: o.orderNumber
                salesChannel:
                    type: string
                    data_name: sc.name
                warehouse:
                    type: string
                    data_name: wh.name
                billingAddress:
                    type: string
                    data_name: ps.billingAddress
                shippingAddress:
                    type: string
                    data_name: ps.shippingAddress
                createdAt:
                    type: datetime
                    data_name: ps.createdAt
                updatedAt:
                    type: datetime
                    data_name: ps.updatedAt
        properties:
            view_link:
                type:   url
                route:  marello_packing_packingslip_view
                params: [ id ]
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye
                rowAction:  true

    marello-order-packingslips:
        extends: marello-packingslips
        source:
            query:
                where:
                    and:
                        - o.id = :orderId
            bind_parameters:
                - orderId
        filters: ~

    marello-packingslip-items:
        source:
            type: orm
            query:
                select:
                    - psi
                from:
                    - { table: MarelloPackingBundle:PackingSlipItem, alias: psi }
                join:
                    left:
                        - { join: psi.packingSlip, alias: ps }
                where:
                    and:
                        - ps.id = :id
            bind_parameters:
                - id
        columns:
            productSku:
                label:            marello.packing.packingslipitem.product_sku.label
            productName:
                label:            marello.packing.packingslipitem.product_name.label
            quantity:
                label:            marello.packing.packingslipitem.quantity.label
            weight:
                label:            marello.packing.packingslipitem.weight.label
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
            updatedAt:
                label:            oro.ui.updated_at
                frontend_type:    datetime
        sorters:
            columns:
                productSku:
                    data_name: psi.productSku
                productName:
                    data_name: psi.productName
                quantity:
                    data_name: psi.quantity
                weight:
                    data_name: ps.weight
                createdAt:
                    data_name: ps.createdAt
                updatedAt:
                    data_name: ps.updatedAt
            default:
                productSku: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        totals:
            grand_total:
                columns:
                    productSku:
                        label: marello.packing.datagrid.columns.grand_total
                    quantity:
                        expr: SUM( CASE WHEN ps.id != :id THEN 0 ELSE psi.quantity END )
                        formatter: integer
                    weight:
                        expr: SUM( CASE WHEN ps.id != :id THEN 0 ELSE psi.weight END )
                        formatter: decimal