repositories:
    package:
        marello: 'https://github.com/marellocommerce/marello.git'
        marello-enterprise: 'https://github.com/marellocommerce/marello-enterprise.git'
        marello-magento-bundle: 'https://github.com/marellocommerce/marello-magento-bundle.git'
        marello-orocommerce-api-bridge: 'https://github.com/marellocommerce/marello-orocommerce-api-bridge.git'
        marello-orocommerce-bridge: 'https://github.com/marellocommerce/marello-orocommerce-bridge.git'
        marello-orocrm-bridge: 'https://github.com/marellocommerce/marello-orocrm-bridge.git'
        marello-subscriptions: 'https://github.com/marellocommerce/marello-subscriptions.git'
        development: 'https://github.com/marellocommerce/marello-dev.git'
        development-ee: 'https://github.com/marellocommerce/marello-ee-dev.git'

    applications:
        marello-application: 'https://github.com/marellocommerce/marello-application.git'
        marello-application-ee: 'https://github.com/marellocommerce/marello-application-ee.git'
        marello-orocommerce-ee-application: 'https://github.com/marellocommerce/marello-orocommerce-ee-application.git'
