placeholders:
    items:
        marello_add_variant_link:
            template:   '@@MarelloProduct/Variant/addVariantLink.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Marello\Bundle\ProductBundle\Entity\Product)'
            acl:        marello_product_create_variant
        marello_add_variant_button:
            template:   '@@MarelloProduct/Variant/addVariantButton.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Marello\Bundle\ProductBundle\Entity\Product)'
            acl:        marello_product_create_variant