services:
    marello_locale.manager.email_template:
        class: 'Marello\Bundle\LocaleBundle\Manager\EmailTemplateManager'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_config.user'
        calls:
            - ['setEntityLocalizationProvider', ['@marello_locale.entity_localization_provider.chain']]

    marello_locale.entity_localization_provider.chain:
        class: 'Marello\Bundle\LocaleBundle\Provider\ChainEntityLocalizationProvider'

    marello_locale.entity_localization_provider.default:
        class: 'Marello\Bundle\LocaleBundle\Provider\DefaultEntityLocalizationProvider'
        arguments:
            - '@oro_config.manager'
            - '@oro_entity.doctrine_helper'
        tags:
            - {name: marello_entity_localization_provider, priority: 0}