oro_system_configuration:
    fields:
        marello_locale.languages_email:
            data_type: array
            type: marello_locale
            priority: 34
            options:
                label: marello.locale.system_configuration.fields.languages_email.label
                tooltip: marello.locale.form.tooltip.languages_email
                required: true
                multiple: true
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            language_settings:
                                children:
                                    language_languages:
                                        children:
                                            - marello_locale.languages_email
