workflows:
    marello_order_b2c_workflow_1:
        attributes:
            payment_reference:
                type: string
            payment_details:
                type: string
            total_paid:
                type: object
                options:
                    class: Oro\Bundle\CurrencyBundle\Entity\Price
            invoiced_at:
                type: object
                options:
                    class: \DateTime
            note:
                type: string
            update_balanced_inventory:
                type: boolean
