services:
    marello_servicepoint.provider.day_of_week:
        class: 'Marello\Bundle\ServicePointBundle\Provider\DayOfWeekProvider'
        arguments:
            - '@oro_locale.settings'

    marello_servicepoint.constraint_validator.day_of_week:
        class: 'Marello\Bundle\ServicePointBundle\Constraint\DayOfWeekValidator'
        arguments:
            - '@marello_servicepoint.provider.day_of_week'
        tags:
            - { name: validator.constraint_validator }

    marello_servicepoint.form_type.day_of_week:
        class: 'Marello\Bundle\ServicePointBundle\Form\Type\DayOfWeekType'
        arguments:
            - '@marello_servicepoint.provider.day_of_week'
        tags:
            - { name: form.type }

    marello_servicepoint.twig_extension.day_of_week:
        class: 'Marello\Bundle\ServicePointBundle\Twig\DayOfWeekExtension'
        arguments:
            - '@marello_servicepoint.provider.day_of_week'
        tags:
            - { name: twig.extension }
